import type { MetadataRoute } from "next";

import brand from "../../../brand.config";
import { siteConfig } from "@/lib/site-data";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: siteConfig.name,
    short_name: brand.businessName,
    description: siteConfig.description,
    start_url: "/",
    display: "standalone",
    background_color: "#f8fafc",
    theme_color: brand.primaryColor,
    // The only icon here used to be the 1200x630 opengraph image, which is a
    // social share card, not an app icon — Android would have stretched it to
    // a square on install. These are the real icon routes, generated by
    // app/icon.tsx and app/apple-icon.tsx.
    icons: [
      { src: "/icon", sizes: "32x32", type: "image/png" },
      { src: "/apple-icon", sizes: "180x180", type: "image/png" },
    ],
  };
}
